# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_server import grpc_server_pb2 as grpc__server_dot_grpc__server__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_server/grpc_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class KafkaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProduceMessage = channel.unary_unary(
                '/kafkaservice.KafkaService/ProduceMessage',
                request_serializer=grpc__server_dot_grpc__server__pb2.ProduceRequest.SerializeToString,
                response_deserializer=grpc__server_dot_grpc__server__pb2.ProduceResponse.FromString,
                _registered_method=True)
        self.ConsumeMessages = channel.unary_stream(
                '/kafkaservice.KafkaService/ConsumeMessages',
                request_serializer=grpc__server_dot_grpc__server__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=grpc__server_dot_grpc__server__pb2.ConsumeResponse.FromString,
                _registered_method=True)


class KafkaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProduceMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KafkaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProduceMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProduceMessage,
                    request_deserializer=grpc__server_dot_grpc__server__pb2.ProduceRequest.FromString,
                    response_serializer=grpc__server_dot_grpc__server__pb2.ProduceResponse.SerializeToString,
            ),
            'ConsumeMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ConsumeMessages,
                    request_deserializer=grpc__server_dot_grpc__server__pb2.ConsumeRequest.FromString,
                    response_serializer=grpc__server_dot_grpc__server__pb2.ConsumeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kafkaservice.KafkaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kafkaservice.KafkaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KafkaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProduceMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kafkaservice.KafkaService/ProduceMessage',
            grpc__server_dot_grpc__server__pb2.ProduceRequest.SerializeToString,
            grpc__server_dot_grpc__server__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsumeMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kafkaservice.KafkaService/ConsumeMessages',
            grpc__server_dot_grpc__server__pb2.ConsumeRequest.SerializeToString,
            grpc__server_dot_grpc__server__pb2.ConsumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
